## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [1]:
import tensorflow as tf

In [71]:
tf.__version__

'2.0.0-beta1'

In [0]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default

In [72]:
tf.executing_eagerly()

True

### Collect Data

In [0]:
from google.colab import drive
drive.mount('/gdrive')

In [2]:
import numpy as np
import pandas as pd

In [246]:
price_data = pd.read_csv('prices.csv')

In [247]:
price_data.head()

,date,symbol,open,close,low,high,volume
0,2016-01-05 00:00:00,WLTW,123.430000,125.839996,122.309998,126.250000,2163600.0
1,2016-01-06 00:00:00,WLTW,125.239998,119.980003,119.940002,125.540001,2386400.0
2,2016-01-07 00:00:00,WLTW,116.379997,114.949997,114.930000,119.739998,2489500.0
3,2016-01-08 00:00:00,WLTW,115.480003,116.620003,113.500000,117.440002,2006300.0
4,2016-01-11 00:00:00,WLTW,117.010002,114.970001,114.089996,117.330002,1408600.0

### Check all columns in the dataset

In [248]:
price_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB

### Drop columns `date` and  `symbol`

In [249]:
price_data = price_data.drop(["date","symbol"], axis = 1)

In [250]:
price_data.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [251]:
price_df=price_data.head(1000)

In [252]:
print("Shape of the updated dataframe : {0}".format(price_df.shape))

Shape of the updated dataframe : (1000, 5)

In [253]:
price_df["volume"]=price_df["volume"]/1000000

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

### Divide the data into train and test sets

In [254]:
from sklearn.model_selection import train_test_split

In [255]:
#Split dataset into Train (80%) and Test (20%)
X =  price_df.drop("volume", axis=1)
Y =  price_df.pop("volume")
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=7)

In [256]:
X_train.shape

(800, 4)

In [257]:
X_test.shape

(200, 4)

#### Convert Training and Test Data to numpy float32 arrays

In [258]:
X_train = np.asarray(X_train, dtype='float32')
X_test = np.asarray(X_test, dtype='float32')
y_train = np.asarray(y_train, dtype='float32')
y_test = np.asarray(y_test, dtype='float32')

In [259]:
type(y_train)

numpy.ndarray

In [260]:
type(X_train)

numpy.ndarray

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [261]:
from sklearn.preprocessing import Normalizer

In [262]:
X_train=Normalizer().fit_transform(X_train)

In [263]:
X_test=Normalizer().fit_transform(X_test)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [264]:
W = tf.Variable(tf.random.normal(shape=[4,1]), name="Weights")
b = tf.Variable(tf.random.normal(shape=[1]),name="Bias")

2.Define a function to calculate prediction

In [265]:
def fn_prediction(x,W,b):
    return tf.add(tf.matmul(x, W),b,name='output')

3.Loss (Cost) Function [Mean square error]

In [266]:
y_pred=fn_prediction(X_train,W,b)

In [267]:
def fn_loss(y,y_):
    return tf.reduce_mean(tf.square(y-y_),name='Loss')

In [268]:
loss = fn_loss(y_train,y_pred)

In [269]:
print(loss)

tf.Tensor(275.69702, shape=(), dtype=float32)

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [270]:
def fn_train(x,y,W,b,learn_rate):
  with tf.GradientTape() as t :
     t.watch([W,b])
     y_pred = fn_prediction(x,W,b)
     loss = fn_loss(y,y_pred)
  
  dc_dw, dc_db = t.gradient(loss, [W, b])
  W = W - learn_rate * dc_dw
  b = b - learn_rate * dc_db
  return W,b

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [271]:
for i in range (100):
  X_train=np.asarray(X_train)
  W,b = fn_train(X_train,y_train,W,b,0.01)
  y_pred = fn_prediction(X_train,W,b)
  train_loss = fn_loss(y_train,y_pred)
  if i % 5 == 0:
    print('Training loss at step: ', i, ' is ', train_loss)

Training loss at step:  0  is  tf.Tensor(273.27106, shape=(), dtype=float32)
Training loss at step:  5  is  tf.Tensor(263.7128, shape=(), dtype=float32)
Training loss at step:  10  is  tf.Tensor(257.3581, shape=(), dtype=float32)
Training loss at step:  15  is  tf.Tensor(253.13322, shape=(), dtype=float32)
Training loss at step:  20  is  tf.Tensor(250.32437, shape=(), dtype=float32)
Training loss at step:  25  is  tf.Tensor(248.45697, shape=(), dtype=float32)
Training loss at step:  30  is  tf.Tensor(247.2154, shape=(), dtype=float32)
Training loss at step:  35  is  tf.Tensor(246.39, shape=(), dtype=float32)
Training loss at step:  40  is  tf.Tensor(245.84125, shape=(), dtype=float32)
Training loss at step:  45  is  tf.Tensor(245.47638, shape=(), dtype=float32)
Training loss at step:  50  is  tf.Tensor(245.2338, shape=(), dtype=float32)
Training loss at step:  55  is  tf.Tensor(245.07256, shape=(), dtype=float32)
Training loss at step:  60  is  tf.Tensor(244.96533, shape=(), dtype=float32)
Training loss at step:  65  is  tf.Tensor(244.89404, shape=(), dtype=float32)
Training loss at step:  70  is  tf.Tensor(244.84665, shape=(), dtype=float32)
Training loss at step:  75  is  tf.Tensor(244.81516, shape=(), dtype=float32)
Training loss at step:  80  is  tf.Tensor(244.7942, shape=(), dtype=float32)
Training loss at step:  85  is  tf.Tensor(244.78027, shape=(), dtype=float32)
Training loss at step:  90  is  tf.Tensor(244.77103, shape=(), dtype=float32)
Training loss at step:  95  is  tf.Tensor(244.76488, shape=(), dtype=float32)

### Get the shapes and values of W and b

In [272]:
W

<tf.Tensor: id=5146971, shape=(4, 1), dtype=float32, numpy=
array([[0.9323867 ],
       [0.16453052],
       [2.15604   ],
       [1.0950297 ]], dtype=float32)>

In [273]:
W.shape

TensorShape([4, 1])

In [274]:
b

In [275]:
b.shape

TensorShape([1])

### Model Prediction on 1st Examples in Test Dataset

In [277]:
y_test_pred = fn_prediction(X_test, W, b)
test_loss = fn_loss(y_test, y_test_pred)

In [278]:
test_loss

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

In [297]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

Using TensorFlow backend.

### Load the given Iris data using pandas (Iris.csv)

In [286]:
iris_data = pd.read_csv('Iris.csv')

In [287]:
iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [288]:
iris_df = pd.get_dummies(iris_data,columns=["Species"], drop_first=False)

In [289]:
iris_df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,1,0,0
1,2,4.9,3.0,1.4,0.2,1,0,0
2,3,4.7,3.2,1.3,0.2,1,0,0
3,4,4.6,3.1,1.5,0.2,1,0,0
4,5,5.0,3.6,1.4,0.2,1,0,0

### Splitting the data into feature set and target set

In [290]:
#Split dataset into Train (80%) and Test (20%)
feature =  iris_df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
target =  iris_df[["Species_Iris-setosa","Species_Iris-versicolor","Species_Iris-virginica"]]

In [292]:
feature.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [293]:
target.head()

   Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                    1                        0                       0
1                    1                        0                       0
2                    1                        0                       0
3                    1                        0                       0
4                    1                        0                       0

In [304]:
train_X, test_X, train_y, test_y = train_test_split(feature, target, test_size=0.20)

In [305]:
train_X.shape

(120, 4)

In [306]:
test_X.shape

(30, 4)

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [315]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(3,activation=tf.nn.softmax, name='output')
])

In [316]:
model.compile(optimizer=tf.keras.optimizers.SGD(), loss='categorical_crossentropy', metrics=['accuracy'])

In [317]:
print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary:
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_4 (Dense)              (None, 10)                50
_________________________________________________________________
output (Dense)               (None, 3)                 33
=================================================================
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________
None

### Model Training

In [318]:
model.fit(train_X, train_y,epochs=200)

Train on 120 samples
Epoch 1/200
120/120 [==============================] - 1s 4ms/sample - loss: 2.2772 - accuracy: 0.3500
Epoch 2/200
120/120 [==============================] - 0s 217us/sample - loss: 1.1837 - accuracy: 0.2500
Epoch 3/200
120/120 [==============================] - 0s 250us/sample - loss: 1.0633 - accuracy: 0.3583
Epoch 4/200
120/120 [==============================] - 0s 408us/sample - loss: 1.0041 - accuracy: 0.3750
Epoch 5/200
120/120 [==============================] - 0s 317us/sample - loss: 0.9569 - accuracy: 0.5750
Epoch 6/200
120/120 [==============================] - 0s 217us/sample - loss: 0.9132 - accuracy: 0.6917
Epoch 7/200
120/120 [==============================] - 0s 267us/sample - loss: 0.8735 - accuracy: 0.6917
Epoch 8/200
120/120 [==============================] - 0s 250us/sample - loss: 0.8432 - accuracy: 0.6917
Epoch 9/200
120/120 [==============================] - 0s 317us/sample - loss: 0.8092 - accuracy: 0.6917
Epoch 10/200
120/120 [==============================] - 0s 292us/sample - loss: 0.7796 - accuracy: 0.6917
Epoch 11/200
120/120 [==============================] - 0s 242us/sample - loss: 0.7607 - accuracy: 0.6917
Epoch 12/200
120/120 [==============================] - 0s 283us/sample - loss: 0.7347 - accuracy: 0.6917
Epoch 13/200
120/120 [==============================] - 0s 233us/sample - loss: 0.7139 - accuracy: 0.6917
Epoch 14/200
120/120 [==============================] - 0s 217us/sample - loss: 0.6980 - accuracy: 0.6917
Epoch 15/200
120/120 [==============================] - 0s 208us/sample - loss: 0.6808 - accuracy: 0.6917
Epoch 16/200
120/120 [==============================] - 0s 167us/sample - loss: 0.6655 - accuracy: 0.6917
Epoch 17/200
120/120 [==============================] - 0s 283us/sample - loss: 0.6524 - accuracy: 0.6917
Epoch 18/200
120/120 [==============================] - 0s 175us/sample - loss: 0.6388 - accuracy: 0.6917
Epoch 19/200
120/120 [==============================] - 0s 275us/sample - loss: 0.6270 - accuracy: 0.6917
Epoch 20/200
120/120 [==============================] - 0s 200us/sample - loss: 0.6143 - accuracy: 0.6917
Epoch 21/200
120/120 [==============================] - 0s 192us/sample - loss: 0.6081 - accuracy: 0.6917
Epoch 22/200
120/120 [==============================] - 0s 250us/sample - loss: 0.5955 - accuracy: 0.6917
Epoch 23/200
120/120 [==============================] - 0s 200us/sample - loss: 0.5924 - accuracy: 0.6917
Epoch 24/200
120/120 [==============================] - 0s 233us/sample - loss: 0.5812 - accuracy: 0.6917
Epoch 25/200
120/120 [==============================] - 0s 200us/sample - loss: 0.5769 - accuracy: 0.7167
Epoch 26/200
120/120 [==============================] - 0s 175us/sample - loss: 0.5632 - accuracy: 0.6917
Epoch 27/200
120/120 [==============================] - 0s 183us/sample - loss: 0.5586 - accuracy: 0.7000
Epoch 28/200
120/120 [==============================] - 0s 325us/sample - loss: 0.5521 - accuracy: 0.6917
Epoch 29/200
120/120 [==============================] - 0s 367us/sample - loss: 0.5437 - accuracy: 0.6917
Epoch 30/200
120/120 [==============================] - 0s 267us/sample - loss: 0.5370 - accuracy: 0.6917
Epoch 31/200
120/120 [==============================] - 0s 267us/sample - loss: 0.5346 - accuracy: 0.7000
Epoch 32/200
120/120 [==============================] - 0s 208us/sample - loss: 0.5262 - accuracy: 0.6917
Epoch 33/200
120/120 [==============================] - 0s 175us/sample - loss: 0.5223 - accuracy: 0.7000
Epoch 34/200
120/120 [==============================] - 0s 192us/sample - loss: 0.5163 - accuracy: 0.6917
Epoch 35/200
120/120 [==============================] - 0s 217us/sample - loss: 0.5108 - accuracy: 0.7000
Epoch 36/200
120/120 [==============================] - 0s 183us/sample - loss: 0.5077 - accuracy: 0.6917
Epoch 37/200
120/120 [==============================] - 0s 150us/sample - loss: 0.5031 - accuracy: 0.7083
Epoch 38/200
120/120 [==============================] - 0s 208us/sample - loss: 0.4973 - accuracy: 0.7167
Epoch 39/200
120/120 [==============================] - 0s 158us/sample - loss: 0.4989 - accuracy: 0.6917
Epoch 40/200
120/120 [==============================] - 0s 150us/sample - loss: 0.4921 - accuracy: 0.7667
Epoch 41/200
120/120 [==============================] - 0s 217us/sample - loss: 0.4856 - accuracy: 0.7083
Epoch 42/200
120/120 [==============================] - 0s 142us/sample - loss: 0.4816 - accuracy: 0.7000
Epoch 43/200
120/120 [==============================] - 0s 192us/sample - loss: 0.4769 - accuracy: 0.7500
Epoch 44/200
120/120 [==============================] - 0s 200us/sample - loss: 0.4744 - accuracy: 0.7333
Epoch 45/200
120/120 [==============================] - 0s 183us/sample - loss: 0.4706 - accuracy: 0.7833
Epoch 46/200
120/120 [==============================] - 0s 200us/sample - loss: 0.4679 - accuracy: 0.7917
Epoch 47/200
120/120 [==============================] - 0s 267us/sample - loss: 0.4668 - accuracy: 0.7417
Epoch 48/200
120/120 [==============================] - 0s 200us/sample - loss: 0.4639 - accuracy: 0.7333
Epoch 49/200
120/120 [==============================] - 0s 150us/sample - loss: 0.4573 - accuracy: 0.7500
Epoch 50/200
120/120 [==============================] - 0s 158us/sample - loss: 0.4543 - accuracy: 0.7833
Epoch 51/200
120/120 [==============================] - 0s 175us/sample - loss: 0.4514 - accuracy: 0.7667
Epoch 52/200
120/120 [==============================] - 0s 142us/sample - loss: 0.4488 - accuracy: 0.7833
Epoch 53/200
120/120 [==============================] - 0s 117us/sample - loss: 0.4456 - accuracy: 0.8167
Epoch 54/200
120/120 [==============================] - 0s 167us/sample - loss: 0.4444 - accuracy: 0.8083
Epoch 55/200
120/120 [==============================] - 0s 150us/sample - loss: 0.4434 - accuracy: 0.7750
Epoch 56/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4378 - accuracy: 0.8417
Epoch 57/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4401 - accuracy: 0.7667
Epoch 58/200
120/120 [==============================] - 0s 217us/sample - loss: 0.4362 - accuracy: 0.8750
Epoch 59/200
120/120 [==============================] - 0s 133us/sample - loss: 0.4294 - accuracy: 0.8583
Epoch 60/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4273 - accuracy: 0.8500
Epoch 61/200
120/120 [==============================] - 0s 133us/sample - loss: 0.4290 - accuracy: 0.8000
Epoch 62/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4232 - accuracy: 0.9333
Epoch 63/200
120/120 [==============================] - 0s 200us/sample - loss: 0.4195 - accuracy: 0.8333
Epoch 64/200
120/120 [==============================] - 0s 433us/sample - loss: 0.4182 - accuracy: 0.9167
Epoch 65/200
120/120 [==============================] - 0s 142us/sample - loss: 0.4180 - accuracy: 0.7833
Epoch 66/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4138 - accuracy: 0.9000
Epoch 67/200
120/120 [==============================] - 0s 208us/sample - loss: 0.4097 - accuracy: 0.8583
Epoch 68/200
120/120 [==============================] - 0s 142us/sample - loss: 0.4076 - accuracy: 0.8667
Epoch 69/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4058 - accuracy: 0.9083
Epoch 70/200
120/120 [==============================] - 0s 150us/sample - loss: 0.4048 - accuracy: 0.8583
Epoch 71/200
120/120 [==============================] - 0s 158us/sample - loss: 0.4028 - accuracy: 0.8750
Epoch 72/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3990 - accuracy: 0.8500
Epoch 73/200
120/120 [==============================] - 0s 142us/sample - loss: 0.3990 - accuracy: 0.8750
Epoch 74/200
120/120 [==============================] - 0s 158us/sample - loss: 0.3969 - accuracy: 0.9250
Epoch 75/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3951 - accuracy: 0.8500
Epoch 76/200
120/120 [==============================] - 0s 150us/sample - loss: 0.3915 - accuracy: 0.9417
Epoch 77/200
120/120 [==============================] - 0s 175us/sample - loss: 0.3894 - accuracy: 0.8583
Epoch 78/200

120/120 [==============================] - 0s 142us/sample - loss: 0.3882 - accuracy: 0.8917
Epoch 79/200
120/120 [==============================] - 0s 167us/sample - loss: 0.3845 - accuracy: 0.8833
Epoch 80/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3824 - accuracy: 0.9417
Epoch 81/200
120/120 [==============================] - 0s 167us/sample - loss: 0.3809 - accuracy: 0.9167
Epoch 82/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3794 - accuracy: 0.9417
Epoch 83/200
120/120 [==============================] - 0s 150us/sample - loss: 0.3778 - accuracy: 0.9417
Epoch 84/200
120/120 [==============================] - 0s 150us/sample - loss: 0.3784 - accuracy: 0.8833
Epoch 85/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3746 - accuracy: 0.8583
Epoch 86/200
120/120 [==============================] - 0s 175us/sample - loss: 0.3718 - accuracy: 0.9667
Epoch 87/200
120/120 [==============================] - 0s 192us/sample - loss: 0.3710 - accuracy: 0.9500
Epoch 88/200
120/120 [==============================] - 0s 208us/sample - loss: 0.3701 - accuracy: 0.8667
Epoch 89/200
120/120 [==============================] - 0s 183us/sample - loss: 0.3659 - accuracy: 0.9250
Epoch 90/200
120/120 [==============================] - 0s 183us/sample - loss: 0.3639 - accuracy: 0.9667
Epoch 91/200
120/120 [==============================] - 0s 208us/sample - loss: 0.3633 - accuracy: 0.9417
Epoch 92/200
120/120 [==============================] - 0s 200us/sample - loss: 0.3619 - accuracy: 0.8667
Epoch 93/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3586 - accuracy: 0.9667
Epoch 94/200
120/120 [==============================] - 0s 142us/sample - loss: 0.3569 - accuracy: 0.9417
Epoch 95/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3549 - accuracy: 0.9333
Epoch 96/200
120/120 [==============================] - 0s 150us/sample - loss: 0.3600 - accuracy: 0.9583
Epoch 97/200
120/120 [==============================] - 0s 192us/sample - loss: 0.3521 - accuracy: 0.9667
Epoch 98/200
120/120 [==============================] - 0s 167us/sample - loss: 0.3538 - accuracy: 0.9083
Epoch 99/200
120/120 [==============================] - 0s 158us/sample - loss: 0.3480 - accuracy: 0.9583
Epoch 100/200
120/120 [==============================] - 0s 217us/sample - loss: 0.3511 - accuracy: 0.9583
Epoch 101/200
120/120 [==============================] - 0s 317us/sample - loss: 0.3460 - accuracy: 0.9417
Epoch 102/200
120/120 [==============================] - 0s 442us/sample - loss: 0.3447 - accuracy: 0.9667
Epoch 103/200
120/120 [==============================] - 0s 150us/sample - loss: 0.3403 - accuracy: 0.9667
Epoch 104/200
120/120 [==============================] - 0s 233us/sample - loss: 0.3402 - accuracy: 0.9583
Epoch 105/200
120/120 [==============================] - 0s 183us/sample - loss: 0.3381 - accuracy: 0.9583
Epoch 106/200
120/120 [==============================] - 0s 183us/sample - loss: 0.3376 - accuracy: 0.9583
Epoch 107/200
120/120 [==============================] - 0s 200us/sample - loss: 0.3339 - accuracy: 0.9583
Epoch 108/200
120/120 [==============================] - 0s 233us/sample - loss: 0.3343 - accuracy: 0.9667
Epoch 109/200
120/120 [==============================] - 0s 117us/sample - loss: 0.3332 - accuracy: 0.9750
Epoch 110/200
120/120 [==============================] - 0s 117us/sample - loss: 0.3306 - accuracy: 0.9333
Epoch 111/200
120/120 [==============================] - ETA: 0s - loss: 0.3584 - accuracy: 0.93 - 0s 108us/sample - loss: 0.3299 - accuracy: 0.9583
Epoch 112/200
120/120 [==============================] - 0s 125us/sample - loss: 0.3300 - accuracy: 0.9750
Epoch 113/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3235 - accuracy: 0.9667
Epoch 114/200
120/120 [==============================] - 0s 92us/sample - loss: 0.3230 - accuracy: 0.9583
Epoch 115/200
120/120 [==============================] - 0s 217us/sample - loss: 0.3224 - accuracy: 0.9667
Epoch 116/200
120/120 [==============================] - 0s 92us/sample - loss: 0.3204 - accuracy: 0.9583
Epoch 117/200
120/120 [==============================] - 0s 150us/sample - loss: 0.3178 - accuracy: 0.9583
Epoch 118/200
120/120 [==============================] - 0s 108us/sample - loss: 0.3165 - accuracy: 0.9667
Epoch 119/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3184 - accuracy: 0.9583
Epoch 120/200
120/120 [==============================] - 0s 117us/sample - loss: 0.3148 - accuracy: 0.9750
Epoch 121/200
120/120 [==============================] - 0s 108us/sample - loss: 0.3121 - accuracy: 0.9667
Epoch 122/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3132 - accuracy: 0.9583
Epoch 123/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3090 - accuracy: 0.9667
Epoch 124/200
120/120 [==============================] - 0s 125us/sample - loss: 0.3080 - accuracy: 0.9583
Epoch 125/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3060 - accuracy: 0.9667
Epoch 126/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3047 - accuracy: 0.9667
Epoch 127/200
120/120 [==============================] - 0s 108us/sample - loss: 0.3030 - accuracy: 0.9667
Epoch 128/200
120/120 [==============================] - 0s 117us/sample - loss: 0.3025 - accuracy: 0.9667
Epoch 129/200
120/120 [==============================] - 0s 142us/sample - loss: 0.3041 - accuracy: 0.9750
Epoch 130/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2986 - accuracy: 0.9667
Epoch 131/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2985 - accuracy: 0.9667
Epoch 132/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2972 - accuracy: 0.9667
Epoch 133/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2949 - accuracy: 0.9667
Epoch 134/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2924 - accuracy: 0.9667
Epoch 135/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2932 - accuracy: 0.9667
Epoch 136/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2911 - accuracy: 0.9667
Epoch 137/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2879 - accuracy: 0.9667
Epoch 138/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2875 - accuracy: 0.9667
Epoch 139/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2870 - accuracy: 0.9667
Epoch 140/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2857 - accuracy: 0.9667
Epoch 141/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2822 - accuracy: 0.9667
Epoch 142/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2828 - accuracy: 0.9583
Epoch 143/200
120/120 [==============================] - 0s 150us/sample - loss: 0.2802 - accuracy: 0.9750
Epoch 144/200
120/120 [==============================] - 0s 150us/sample - loss: 0.2793 - accuracy: 0.9667
Epoch 145/200
120/120 [==============================] - 0s 192us/sample - loss: 0.2812 - accuracy: 0.9750
Epoch 146/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2773 - accuracy: 0.9667
Epoch 147/200
120/120 [==============================] - 0s 150us/sample - loss: 0.2749 - accuracy: 0.9667
Epoch 148/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2731 - accuracy: 0.9667
Epoch 149/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2743 - accuracy: 0.9667
Epoch 150/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2735 - accuracy: 0.9667
Epoch 151/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2700 - accuracy: 0.9667
Epoch 152/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2713 - accuracy: 0.9750
Epoch 153/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2689 - accuracy: 0.9667
Epoch 154/200

120/120 [==============================] - 0s 100us/sample - loss: 0.2666 - accuracy: 0.9667
Epoch 155/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2659 - accuracy: 0.9667
Epoch 156/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2656 - accuracy: 0.9667
Epoch 157/200
120/120 [==============================] - 0s 83us/sample - loss: 0.2621 - accuracy: 0.9667
Epoch 158/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2610 - accuracy: 0.9667
Epoch 159/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2649 - accuracy: 0.9750
Epoch 160/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2596 - accuracy: 0.9667
Epoch 161/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2622 - accuracy: 0.9667
Epoch 162/200
120/120 [==============================] - 0s 142us/sample - loss: 0.2566 - accuracy: 0.9667
Epoch 163/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2572 - accuracy: 0.9667
Epoch 164/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2549 - accuracy: 0.9667
Epoch 165/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2525 - accuracy: 0.9750
Epoch 166/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2528 - accuracy: 0.9667
Epoch 167/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2528 - accuracy: 0.9750
Epoch 168/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2531 - accuracy: 0.9833
Epoch 169/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2521 - accuracy: 0.9667
Epoch 170/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2485 - accuracy: 0.9750
Epoch 171/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2449 - accuracy: 0.9667
Epoch 172/200
120/120 [==============================] - ETA: 0s - loss: 0.2105 - accuracy: 0.96 - 0s 100us/sample - loss: 0.2464 - accuracy: 0.9667
Epoch 173/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2436 - accuracy: 0.9667
Epoch 174/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2424 - accuracy: 0.9667
Epoch 175/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2410 - accuracy: 0.9750
Epoch 176/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2447 - accuracy: 0.9667
Epoch 177/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2398 - accuracy: 0.9667
Epoch 178/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2385 - accuracy: 0.9667
Epoch 179/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2372 - accuracy: 0.9750
Epoch 180/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2351 - accuracy: 0.9667
Epoch 181/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2353 - accuracy: 0.9667
Epoch 182/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2335 - accuracy: 0.9667
Epoch 183/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2329 - accuracy: 0.9667
Epoch 184/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2336 - accuracy: 0.9667
Epoch 185/200
120/120 [==============================] - 0s 142us/sample - loss: 0.2301 - accuracy: 0.9667
Epoch 186/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2293 - accuracy: 0.9667
Epoch 187/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2295 - accuracy: 0.9667
Epoch 188/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2284 - accuracy: 0.9667
Epoch 189/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2278 - accuracy: 0.9833
Epoch 190/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2267 - accuracy: 0.9667
Epoch 191/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2268 - accuracy: 0.9750
Epoch 192/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2250 - accuracy: 0.9750
Epoch 193/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2249 - accuracy: 0.9750
Epoch 194/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2285 - accuracy: 0.9667
Epoch 195/200
120/120 [==============================] - 0s 83us/sample - loss: 0.2223 - accuracy: 0.9833
Epoch 196/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2196 - accuracy: 0.9667
Epoch 197/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2200 - accuracy: 0.9833
Epoch 198/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2191 - accuracy: 0.9667
Epoch 199/200
120/120 [==============================] - 0s 192us/sample - loss: 0.2182 - accuracy: 0.9833
Epoch 200/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2174 - accuracy: 0.9667

### Model Prediction

In [319]:
results = model.evaluate(test_X, test_y)

30/30 [==============================] - 0s 2ms/sample - loss: 0.2668 - accuracy: 0.9667

In [320]:
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss: 0.266777
Final test set accuracy: 0.966667

### Save the Model

In [321]:
model.save('iris_model.hs')

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?

In [328]:
model_2layer = tf.keras.Sequential([
  tf.keras.layers.Dense(20, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(20, activation=tf.nn.relu),
  tf.keras.layers.Dense(3,activation=tf.nn.softmax, name='output')
])

In [329]:
model_2layer.compile(optimizer=tf.keras.optimizers.SGD(), loss='categorical_crossentropy', metrics=['accuracy'])

In [330]:
print('Neural Network Model Summary: ')
print(model_2layer.summary())

Neural Network Model Summary:
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_7 (Dense)              (None, 20)                100
_________________________________________________________________
dense_8 (Dense)              (None, 20)                420
_________________________________________________________________
output (Dense)               (None, 3)                 63
=================================================================
Total params: 583
Trainable params: 583
Non-trainable params: 0
_________________________________________________________________
None

In [331]:
model_2layer.fit(train_X, train_y,epochs=200)

Train on 120 samples
Epoch 1/200
120/120 [==============================] - 0s 3ms/sample - loss: 1.7897 - accuracy: 0.3083
Epoch 2/200
120/120 [==============================] - 0s 133us/sample - loss: 1.2260 - accuracy: 0.3083
Epoch 3/200
120/120 [==============================] - 0s 258us/sample - loss: 1.0095 - accuracy: 0.4417
Epoch 4/200
120/120 [==============================] - 0s 158us/sample - loss: 0.9238 - accuracy: 0.7083
Epoch 5/200
120/120 [==============================] - 0s 225us/sample - loss: 0.8787 - accuracy: 0.9083
Epoch 6/200
120/120 [==============================] - 0s 200us/sample - loss: 0.8538 - accuracy: 0.7417
Epoch 7/200
120/120 [==============================] - 0s 175us/sample - loss: 0.8312 - accuracy: 0.8083
Epoch 8/200
120/120 [==============================] - 0s 150us/sample - loss: 0.8120 - accuracy: 0.7083
Epoch 9/200
120/120 [==============================] - 0s 183us/sample - loss: 0.7990 - accuracy: 0.7333
Epoch 10/200
120/120 [==============================] - 0s 150us/sample - loss: 0.7756 - accuracy: 0.7000
Epoch 11/200
120/120 [==============================] - 0s 150us/sample - loss: 0.7597 - accuracy: 0.7000
Epoch 12/200
120/120 [==============================] - 0s 142us/sample - loss: 0.7409 - accuracy: 0.7083
Epoch 13/200
120/120 [==============================] - 0s 150us/sample - loss: 0.7244 - accuracy: 0.7000
Epoch 14/200
120/120 [==============================] - 0s 133us/sample - loss: 0.7094 - accuracy: 0.6917
Epoch 15/200
120/120 [==============================] - 0s 142us/sample - loss: 0.6962 - accuracy: 0.7000
Epoch 16/200
120/120 [==============================] - 0s 217us/sample - loss: 0.6774 - accuracy: 0.7083
Epoch 17/200
120/120 [==============================] - 0s 150us/sample - loss: 0.6625 - accuracy: 0.7333
Epoch 18/200
120/120 [==============================] - 0s 317us/sample - loss: 0.6484 - accuracy: 0.7333
Epoch 19/200
120/120 [==============================] - 0s 258us/sample - loss: 0.6355 - accuracy: 0.6917
Epoch 20/200
120/120 [==============================] - ETA: 0s - loss: 0.6294 - accuracy: 0.78 - 0s 192us/sample - loss: 0.6220 - accuracy: 0.8500
Epoch 21/200
120/120 [==============================] - ETA: 0s - loss: 0.7143 - accuracy: 0.56 - 0s 167us/sample - loss: 0.6142 - accuracy: 0.7667
Epoch 22/200
120/120 [==============================] - 0s 150us/sample - loss: 0.5983 - accuracy: 0.7167
Epoch 23/200
120/120 [==============================] - 0s 158us/sample - loss: 0.5852 - accuracy: 0.7750
Epoch 24/200
120/120 [==============================] - 0s 175us/sample - loss: 0.5822 - accuracy: 0.7500
Epoch 25/200
120/120 [==============================] - 0s 142us/sample - loss: 0.5618 - accuracy: 0.8250
Epoch 26/200
120/120 [==============================] - 0s 150us/sample - loss: 0.5565 - accuracy: 0.8000
Epoch 27/200
120/120 [==============================] - 0s 150us/sample - loss: 0.5515 - accuracy: 0.7500
Epoch 28/200
120/120 [==============================] - 0s 133us/sample - loss: 0.5329 - accuracy: 0.8583
Epoch 29/200
120/120 [==============================] - 0s 150us/sample - loss: 0.5233 - accuracy: 0.8583
Epoch 30/200
120/120 [==============================] - 0s 133us/sample - loss: 0.5133 - accuracy: 0.8500
Epoch 31/200
120/120 [==============================] - 0s 142us/sample - loss: 0.5055 - accuracy: 0.8667
Epoch 32/200
120/120 [==============================] - 0s 108us/sample - loss: 0.4959 - accuracy: 0.8500
Epoch 33/200
120/120 [==============================] - 0s 142us/sample - loss: 0.4882 - accuracy: 0.8833
Epoch 34/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4779 - accuracy: 0.8917
Epoch 35/200
120/120 [==============================] - 0s 117us/sample - loss: 0.4709 - accuracy: 0.9000
Epoch 36/200
120/120 [==============================] - 0s 192us/sample - loss: 0.4586 - accuracy: 0.8917
Epoch 37/200
120/120 [==============================] - 0s 117us/sample - loss: 0.4537 - accuracy: 0.9167
Epoch 38/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4475 - accuracy: 0.9583
Epoch 39/200
120/120 [==============================] - 0s 183us/sample - loss: 0.4393 - accuracy: 0.8667
Epoch 40/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4313 - accuracy: 0.8917
Epoch 41/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4257 - accuracy: 0.9583
Epoch 42/200
120/120 [==============================] - 0s 117us/sample - loss: 0.4201 - accuracy: 0.9417
Epoch 43/200
120/120 [==============================] - 0s 142us/sample - loss: 0.4166 - accuracy: 0.9250
Epoch 44/200
120/120 [==============================] - ETA: 0s - loss: 0.4186 - accuracy: 0.90 - 0s 108us/sample - loss: 0.4077 - accuracy: 0.9417
Epoch 45/200
120/120 [==============================] - 0s 125us/sample - loss: 0.4046 - accuracy: 0.9583
Epoch 46/200
120/120 [==============================] - 0s 142us/sample - loss: 0.3980 - accuracy: 0.9583
Epoch 47/200
120/120 [==============================] - 0s 133us/sample - loss: 0.3924 - accuracy: 0.9417
Epoch 48/200
120/120 [==============================] - 0s 125us/sample - loss: 0.3888 - accuracy: 0.9500
Epoch 49/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3835 - accuracy: 0.9667
Epoch 50/200
120/120 [==============================] - 0s 142us/sample - loss: 0.3818 - accuracy: 0.9333
Epoch 51/200
120/120 [==============================] - 0s 142us/sample - loss: 0.3748 - accuracy: 0.9667
Epoch 52/200
120/120 [==============================] - 0s 150us/sample - loss: 0.3721 - accuracy: 0.9500
Epoch 53/200
120/120 [==============================] - 0s 117us/sample - loss: 0.3706 - accuracy: 0.9250
Epoch 54/200
120/120 [==============================] - 0s 167us/sample - loss: 0.3629 - accuracy: 0.9417
Epoch 55/200
120/120 [==============================] - 0s 125us/sample - loss: 0.3584 - accuracy: 0.9667
Epoch 56/200
120/120 [==============================] - 0s 108us/sample - loss: 0.3537 - accuracy: 0.9667
Epoch 57/200
120/120 [==============================] - 0s 117us/sample - loss: 0.3505 - accuracy: 0.9583
Epoch 58/200
120/120 [==============================] - ETA: 0s - loss: 0.3584 - accuracy: 0.93 - 0s 108us/sample - loss: 0.3533 - accuracy: 0.9250
Epoch 59/200
120/120 [==============================] - 0s 167us/sample - loss: 0.3428 - accuracy: 0.9667
Epoch 60/200
120/120 [==============================] - 0s 183us/sample - loss: 0.3380 - accuracy: 0.9667
Epoch 61/200
120/120 [==============================] - 0s 258us/sample - loss: 0.3351 - accuracy: 0.9667
Epoch 62/200
120/120 [==============================] - 0s 183us/sample - loss: 0.3313 - accuracy: 0.9583
Epoch 63/200
120/120 [==============================] - 0s 225us/sample - loss: 0.3274 - accuracy: 0.9667
Epoch 64/200
120/120 [==============================] - 0s 283us/sample - loss: 0.3327 - accuracy: 0.9500
Epoch 65/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3221 - accuracy: 0.9667
Epoch 66/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3187 - accuracy: 0.9667
Epoch 67/200
120/120 [==============================] - 0s 108us/sample - loss: 0.3181 - accuracy: 0.9667
Epoch 68/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3127 - accuracy: 0.9750
Epoch 69/200
120/120 [==============================] - 0s 108us/sample - loss: 0.3072 - accuracy: 0.9667
Epoch 70/200
120/120 [==============================] - 0s 92us/sample - loss: 0.3039 - accuracy: 0.9667
Epoch 71/200
120/120 [==============================] - 0s 100us/sample - loss: 0.3048 - accuracy: 0.9667
Epoch 72/200
120/120 [==============================] - 0s 125us/sample - loss: 0.3018 - accuracy: 0.9667
Epoch 73/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2961 - accuracy: 0.9667
Epoch 74/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2919 - accuracy: 0.9667
Epoch 75/200
120/120 [==============================] - 0s 150us/sample - loss: 0.2907 - accuracy: 0.9667
Epoch 76/200

120/120 [==============================] - 0s 117us/sample - loss: 0.2888 - accuracy: 0.9833
Epoch 77/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2853 - accuracy: 0.9667
Epoch 78/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2817 - accuracy: 0.9667
Epoch 79/200
120/120 [==============================] - 0s 158us/sample - loss: 0.2833 - accuracy: 0.9667
Epoch 80/200
120/120 [==============================] - 0s 150us/sample - loss: 0.2747 - accuracy: 0.9667
Epoch 81/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2763 - accuracy: 0.9667
Epoch 82/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2703 - accuracy: 0.9667
Epoch 83/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2666 - accuracy: 0.9750
Epoch 84/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2671 - accuracy: 0.9667
Epoch 85/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2619 - accuracy: 0.9667
Epoch 86/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2623 - accuracy: 0.9583
Epoch 87/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2590 - accuracy: 0.9667
Epoch 88/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2542 - accuracy: 0.9667
Epoch 89/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2559 - accuracy: 0.9667
Epoch 90/200
120/120 [==============================] - 0s 133us/sample - loss: 0.2507 - accuracy: 0.9667
Epoch 91/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2477 - accuracy: 0.9667
Epoch 92/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2466 - accuracy: 0.9667
Epoch 93/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2429 - accuracy: 0.9583
Epoch 94/200
120/120 [==============================] - 0s 150us/sample - loss: 0.2388 - accuracy: 0.9667
Epoch 95/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2366 - accuracy: 0.9667
Epoch 96/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2345 - accuracy: 0.9667
Epoch 97/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2326 - accuracy: 0.9667
Epoch 98/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2300 - accuracy: 0.9667
Epoch 99/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2285 - accuracy: 0.9667
Epoch 100/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2260 - accuracy: 0.9750
Epoch 101/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2266 - accuracy: 0.9750
Epoch 102/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2222 - accuracy: 0.9833
Epoch 103/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2205 - accuracy: 0.9750
Epoch 104/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2176 - accuracy: 0.9667
Epoch 105/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2181 - accuracy: 0.9750
Epoch 106/200
120/120 [==============================] - 0s 125us/sample - loss: 0.2281 - accuracy: 0.9667
Epoch 107/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2124 - accuracy: 0.9667
Epoch 108/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2113 - accuracy: 0.9750
Epoch 109/200
120/120 [==============================] - 0s 92us/sample - loss: 0.2076 - accuracy: 0.9667
Epoch 110/200
120/120 [==============================] - 0s 100us/sample - loss: 0.2081 - accuracy: 0.9833
Epoch 111/200
120/120 [==============================] - 0s 175us/sample - loss: 0.2091 - accuracy: 0.9750
Epoch 112/200
120/120 [==============================] - 0s 217us/sample - loss: 0.2054 - accuracy: 0.9750
Epoch 113/200
120/120 [==============================] - 0s 158us/sample - loss: 0.2012 - accuracy: 0.9833
Epoch 114/200
120/120 [==============================] - 0s 133us/sample - loss: 0.1985 - accuracy: 0.9667
Epoch 115/200
120/120 [==============================] - 0s 192us/sample - loss: 0.2035 - accuracy: 0.9750
Epoch 116/200
120/120 [==============================] - 0s 125us/sample - loss: 0.1975 - accuracy: 0.9750
Epoch 117/200
120/120 [==============================] - 0s 117us/sample - loss: 0.1969 - accuracy: 0.9667
Epoch 118/200
120/120 [==============================] - 0s 108us/sample - loss: 0.2016 - accuracy: 0.9583
Epoch 119/200
120/120 [==============================] - 0s 117us/sample - loss: 0.2031 - accuracy: 0.9667
Epoch 120/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1945 - accuracy: 0.9833
Epoch 121/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1960 - accuracy: 0.9667
Epoch 122/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1886 - accuracy: 0.9667
Epoch 123/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1858 - accuracy: 0.9667
Epoch 124/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1864 - accuracy: 0.9667
Epoch 125/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1815 - accuracy: 0.9750
Epoch 126/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1800 - accuracy: 0.9833
Epoch 127/200
120/120 [==============================] - 0s 150us/sample - loss: 0.1815 - accuracy: 0.9750
Epoch 128/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1884 - accuracy: 0.9583
Epoch 129/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1786 - accuracy: 0.9667
Epoch 130/200
120/120 [==============================] - 0s 117us/sample - loss: 0.1734 - accuracy: 0.9667
Epoch 131/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1749 - accuracy: 0.9833
Epoch 132/200
120/120 [==============================] - 0s 125us/sample - loss: 0.1750 - accuracy: 0.9667
Epoch 133/200
120/120 [==============================] - 0s 117us/sample - loss: 0.1717 - accuracy: 0.9667
Epoch 134/200
120/120 [==============================] - 0s 117us/sample - loss: 0.1686 - accuracy: 0.9750
Epoch 135/200
120/120 [==============================] - 0s 167us/sample - loss: 0.1703 - accuracy: 0.9750
Epoch 136/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1697 - accuracy: 0.9750
Epoch 137/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1664 - accuracy: 0.9833
Epoch 138/200
120/120 [==============================] - 0s 133us/sample - loss: 0.1641 - accuracy: 0.9750
Epoch 139/200
120/120 [==============================] - 0s 117us/sample - loss: 0.1631 - accuracy: 0.9833
Epoch 140/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1673 - accuracy: 0.9750
Epoch 141/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1708 - accuracy: 0.9667
Epoch 142/200
120/120 [==============================] - 0s 117us/sample - loss: 0.1595 - accuracy: 0.9667
Epoch 143/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1764 - accuracy: 0.9750
Epoch 144/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1591 - accuracy: 0.9750
Epoch 145/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1586 - accuracy: 0.9667
Epoch 146/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1587 - accuracy: 0.9750
Epoch 147/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1581 - accuracy: 0.9750
Epoch 148/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1529 - accuracy: 0.9833
Epoch 149/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1542 - accuracy: 0.9833
Epoch 150/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1643 - accuracy: 0.9750
Epoch 151/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1540 - accuracy: 0.9750
Epoch 152/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1585 - accuracy: 0.9667
Epoch 153/200

120/120 [==============================] - 0s 100us/sample - loss: 0.1526 - accuracy: 0.9667
Epoch 154/200
120/120 [==============================] - 0s 67us/sample - loss: 0.1529 - accuracy: 0.9667
Epoch 155/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1476 - accuracy: 0.9667
Epoch 156/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1470 - accuracy: 0.9750
Epoch 157/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1476 - accuracy: 0.9833
Epoch 158/200
120/120 [==============================] - 0s 67us/sample - loss: 0.1509 - accuracy: 0.9750
Epoch 159/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1420 - accuracy: 0.9833
Epoch 160/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1410 - accuracy: 0.9833
Epoch 161/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1422 - accuracy: 0.9750
Epoch 162/200
120/120 [==============================] - 0s 117us/sample - loss: 0.1432 - accuracy: 0.9750
Epoch 163/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1492 - accuracy: 0.9667
Epoch 164/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1405 - accuracy: 0.9667
Epoch 165/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1470 - accuracy: 0.9750
Epoch 166/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1417 - accuracy: 0.9750
Epoch 167/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1394 - accuracy: 0.9833
Epoch 168/200
120/120 [==============================] - 0s 150us/sample - loss: 0.1361 - accuracy: 0.9667
Epoch 169/200
120/120 [==============================] - 0s 142us/sample - loss: 0.1395 - accuracy: 0.9667
Epoch 170/200
120/120 [==============================] - 0s 167us/sample - loss: 0.1351 - accuracy: 0.9750
Epoch 171/200
120/120 [==============================] - 0s 133us/sample - loss: 0.1315 - accuracy: 0.9833
Epoch 172/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1316 - accuracy: 0.9750
Epoch 173/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1316 - accuracy: 0.9750
Epoch 174/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1353 - accuracy: 0.9833
Epoch 175/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1450 - accuracy: 0.9583
Epoch 176/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1359 - accuracy: 0.9667
Epoch 177/200
120/120 [==============================] - 0s 108us/sample - loss: 0.1505 - accuracy: 0.9583
Epoch 178/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1349 - accuracy: 0.9750
Epoch 179/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1330 - accuracy: 0.9667
Epoch 180/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1313 - accuracy: 0.9833
Epoch 181/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1319 - accuracy: 0.9750
Epoch 182/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1267 - accuracy: 0.9833
Epoch 183/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1248 - accuracy: 0.9833
Epoch 184/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1282 - accuracy: 0.9750
Epoch 185/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1231 - accuracy: 0.9833
Epoch 186/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1216 - accuracy: 0.9833
Epoch 187/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1255 - accuracy: 0.9750
Epoch 188/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1291 - accuracy: 0.9750
Epoch 189/200
120/120 [==============================] - 0s 117us/sample - loss: 0.1200 - accuracy: 0.9750
Epoch 190/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1225 - accuracy: 0.9750
Epoch 191/200
120/120 [==============================] - 0s 100us/sample - loss: 0.1193 - accuracy: 0.9833
Epoch 192/200
120/120 [==============================] - 0s 67us/sample - loss: 0.1232 - accuracy: 0.9667
Epoch 193/200
120/120 [==============================] - 0s 83us/sample - loss: 0.1215 - accuracy: 0.9833
Epoch 194/200
120/120 [==============================] - 0s 67us/sample - loss: 0.1352 - accuracy: 0.9500
Epoch 195/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1224 - accuracy: 0.9750
Epoch 196/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1169 - accuracy: 0.9917
Epoch 197/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1232 - accuracy: 0.9833
Epoch 198/200
120/120 [==============================] - 0s 92us/sample - loss: 0.1244 - accuracy: 0.9667
Epoch 199/200
120/120 [==============================] - 0s 67us/sample - loss: 0.1153 - accuracy: 0.9667
Epoch 200/200
120/120 [==============================] - 0s 75us/sample - loss: 0.1165 - accuracy: 0.9750

In [332]:
results = model_2layer.evaluate(test_X, test_y)

30/30 [==============================] - 0s 5ms/sample - loss: 0.1601 - accuracy: 0.9667

In [333]:
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss: 0.160073
Final test set accuracy: 0.966667